#!/usr/bin/env bash




##
## ## Clear
##

zrwm-msg clear-rules
zrwm-msg clear-binds




##
## ## Appearance
##

zrwm-msg borderpx 4
zrwm-msg bordercolor 444444ff
zrwm-msg focuscolor 8baa9bff
zrwm-msg setcursor Adwaita 24
zrwm-msg setlayout 0




##
## ## Mousebind
##

zrwm-msg bind-mouse super left moveresize 1
zrwm-msg bind-mouse super middle togglefloating 0
zrwm-msg bind-mouse super right moveresize 2




##
## ## Keybind
##




##
## ## Keybind / System
##

zrwm-msg bind alt,shift x spawn wlogout
zrwm-msg bind alt,ctrl x spawn pkill river
zrwm-msg bind alt,shift c reload




##
## ## Keybind / Tag
##

mod_tag_keybind () {
	zrwm-msg bind super $(($1 + 1)) view $((1 << $1))
	zrwm-msg bind super,ctrl $(($1 + 1)) toggleview $((1 << $1))
	zrwm-msg bind super,shift $(($1 + 1)) tag $((1 << $1))
	zrwm-msg bind super,shift,ctrl $(($1 + 1)) toggletag $((1 << $1))
}

mod_tag_keybind 0
mod_tag_keybind 1
mod_tag_keybind 2
mod_tag_keybind 3
mod_tag_keybind 4
mod_tag_keybind 5
mod_tag_keybind 6
mod_tag_keybind 7
mod_tag_keybind 8




##
## ## Keybind / Window
##




##
## ## Keybind / Window / close
##

zrwm-msg bind super q killwindow




##
## ## Keybind / Window / focus
##

zrwm-msg bind super a focusstack -1
zrwm-msg bind super s  focusstack 1




##
## ## Keybind / Window / swap
##

zrwm-msg bind super grave pushup
zrwm-msg bind super Tab pushdown



##
## ## Keybind / Window / control
##

zrwm-msg bind super h setmfact -0.05
zrwm-msg bind super l setmfact 0.05




##
## ## Keybind /  Window / toggle
##

zrwm-msg bind super f togglefullscreen
zrwm-msg bind super Escape togglefloating
zrwm-msg bind super o togglesplit
zrwm-msg bind super p togglesticky




##
## ## Keybind / Layout
##

zrwm-msg bind super,alt f setlayout float
zrwm-msg bind super,alt t setlayout split_tile

zrwm-msg bind super,alt d setlayout deck
zrwm-msg bind super,alt u setlayout deck




##
## ## Keybind / Application / LauncherF
##

#zrwm-msg bind super d spawn fuzzel
zrwm-msg bind alt,shift d spawn rofi -show drun
zrwm-msg bind alt,shift r spawn rofi -show run




##
## ## Keybind / Application / Terminal
##

#zrwm-msg bind super Return spawn foot tmux
zrwm-msg bind alt Return spawn xfce4-terminal
zrwm-msg bind alt,shift a spawn xfce4-terminal
zrwm-msg bind alt,ctrl a spawn foot
zrwm-msg bind alt,shift t spawn sakura
zrwm-msg bind alt,ctrl t spawn kitty




##
## ## Keybind / Application / Fav
##

zrwm-msg bind alt,shift f spawn thunar
zrwm-msg bind alt,shift g spawn pcmanfm
zrwm-msg bind alt,shift e spawn mousepad
zrwm-msg bind alt,shift b spawn firefox --new-tab about:blank
zrwm-msg bind alt,shift v spawn pavucontrol
zrwm-msg bind alt,shift n spawn kitty --class 'nmtui' --title 'Network Settings' nmtui




##
## ## Keybind / Screenshot
##

zrwm-msg bind none Print spawn xfce4-screenshooter --fullscreen
zrwm-msg bind super Print spawn xfce4-screenshooter --window
zrwm-msg bind ctrl Print spawn xfce4-screenshooter --region
zrwm-msg bind alt Print spawn xfce4-screenshooter




##
## ## Keybind / Brightness
##

zrwm-msg bind none XF86MonBrightnessDown spawn brightnessctl set +5%
zrwm-msg bind none XF86MonBrightnessUp spawn brightnessctl set 5%-




##
## ## Keybind / Audio
##

zrwm-msg bind none XF86AudioMute spawn pamixer --toggle-mute
zrwm-msg bind none XF86AudioRaiseVolume spawn pamixer -i 5
zrwm-msg bind none XF86AudioLowerVolume spawn pamixer -d 5


#zrwm-msg bind none XF86AudioRaiseVolume spawn wpctl set-volume @DEFAULT_AUDIO_SINK@ 2.5%+
#zrwm-msg bind none XF86AudioLowerVolume spawn wpctl set-volume @DEFAULT_AUDIO_SINK@ 2.5%-
#zrwm-msg bind none XF86AudioMute spawn wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle


zrwm-msg bind none XF86AudioMedia spawn playerctl play-pause
zrwm-msg bind none XF86AudioPlay spawn playerctl play
zrwm-msg bind none XF86AudioPause spawn playerctl pause
zrwm-msg bind none XF86AudioPrev spawn playerctl previous
zrwm-msg bind none XF86AudioNext spawn playerctl next




##
## ## Rule
##

zrwm-msg rule-add -appid steam -float -inverse_title Steam
zrwm-msg rule-add -appid xdg-desktop-portal-gtk -float
zrwm-msg rule-add -appid "steam_app_" -float
zrwm-msg rule-add -appid firefox -title "Picture-in-Picture" -float




##
## ## autostart
##

~/.config/zrwm/autostart &
